const scenarios={
 scheduling:{title:'Interview scheduling',posture:'Launch with bounded exceptions',promise:'Reduce coordination drag without hiding candidate or interviewer constraints.',source:'Ashby interview plan + approved availability rules',mode:'Deterministic workflow first; AI only for exception classification and message drafting',authority:'Coordinator owns exceptions; hiring team retains interview design and final scheduling choices',fallback:'Visible exception queue with reason, owner, and response target',steward:'Recruiting Operations',proof:'Manual touches, time-to-schedule, reschedule rate, exception recovery, adoption'},
 communication:{title:'Candidate communication',posture:'Pilot with human approval',promise:'Increase consistency and responsiveness while preserving honest, human candidate care.',source:'Ashby stage + approved message library + role context',mode:'AI drafts within approved patterns; automation handles triggers and delivery rules',authority:'Recruiter approves sensitive, rejection, compensation, and exception messages',fallback:'Block send when context is incomplete, conflicting, or high impact',steward:'Recruiting pod owner',proof:'Response latency, edit rate, candidate questions, opt-outs, error and escalation patterns'},
 offer:{title:'Offer-to-hire handoff',posture:'Repair the data contract first',promise:'Make the accepted-offer handoff complete, attributable, and recoverable across systems.',source:'Ashby accepted offer + validated required-field checklist',mode:'Deterministic integration, validation, and reconciliation; no generative decisioning',authority:'People Operations validates exceptions and owns final employee record readiness',fallback:'Stop the handoff, name missing fields, assign owner, preserve an audit trail',steward:'People Operations + People Systems',proof:'Field completeness, correction loops, handoff latency, duplicate entry, onboarding readiness'},
 reporting:{title:'People reporting pipeline',posture:'Build a governed prototype',promise:'Turn recurring reporting requests into reusable, documented views without inventing certainty.',source:'Approved system exports + metric definitions + refresh timestamps',mode:'Scripts for extraction and validation; AI for summarization with source-linked claims',authority:'People leader interprets findings and approves decisions; metric owner controls definitions',fallback:'Show missing data, stale refreshes, and definition conflicts instead of filling gaps',steward:'People Analytics / requesting owner',proof:'Preparation time, definition drift, reuse, correction rate, decision follow-through'}
};
const outputs={promise:'workflowPromise',source:'sourceTruth',mode:'automationMode',authority:'humanAuthority',fallback:'failurePath',steward:'workflowSteward',proof:'operatingProof'};
function runWarranty(key){const data=scenarios[key];document.querySelectorAll('.scenario-btn').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.scenario===key)));document.getElementById('scenarioTitle').textContent=data.title;document.getElementById('scenarioPosture').textContent=data.posture;Object.entries(outputs).forEach(([k,id])=>{document.getElementById(id).textContent=data[k]});document.getElementById('verdictTitle').textContent=data.posture;document.getElementById('verdictText').textContent=data.promise;const card=document.querySelector('.studio-panel');card.classList.remove('pulse');void card.offsetWidth;card.classList.add('pulse');document.getElementById('scenarioAnnouncement').textContent=`${data.title}. ${data.posture}.`}
function replayHero(){const card=document.getElementById('heroWarranty');card.classList.remove('is-running','is-settled');void card.offsetWidth;card.classList.add('is-running');setTimeout(()=>{card.classList.remove('is-running');card.classList.add('is-settled')},2600)}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.scenario-btn').forEach(b=>b.addEventListener('click',()=>runWarranty(b.dataset.scenario)));document.getElementById('studioReplay')?.addEventListener('click',()=>runWarranty(document.querySelector('.scenario-btn[aria-pressed="true"]').dataset.scenario));document.getElementById('heroReplay')?.addEventListener('click',replayHero);if(!matchMedia('(prefers-reduced-motion: reduce)').matches) replayHero(); else document.getElementById('heroWarranty')?.classList.add('is-settled')});
